theme: jekyll-theme-cayman
title: Hooray for graphs!
description: Honestly I just wanted to create some graphs that wouldn't make my eyes bleed.  Eventually they'll tell a story.  All graphs tell some story.
